server:
  port: 8761

eureka:
  instance:
    hostname: eureka-server-01

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  server:
    wait-time-in-ms-when-sync-empty: 1
    enable-self-preservation: false