server:
  port: 8081

spring:
  application:
    name: eureka-client-01

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server-01:8761/eureka/
