server:
  port: 9090

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/NeverFeel/spring-cloud-redefine.git
          search-paths: config-file
